performance:
  name: smoke-test-performance-write
  mode: write
  use_docker: true
  warmup_seconds: 1
  duration_seconds: 3
  samples_per_second: 2
  concurrency:
    writers: [1, 4]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 0
    prepopulate_streams: 0
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - fact
    - boomerang
    - dummy
---
performance:
  name: smoke-test-performance-read
  mode: read
  use_docker: true
  warmup_seconds: 1
  duration_seconds: 3
  samples_per_second: 2
  concurrency:
    readers: [1, 4]
  operations:
    read:
      limit: 10
    write:
      event_size_bytes: 256
  setup:
    prepopulate_events: 500
    prepopulate_streams: 50
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - fact
    - boomerang
    - dummy
