performance:
  name: scaling-readers
  mode: read
  use_docker: true
  warmup_seconds: 0
  duration_seconds: 20
  samples_per_second: 10
  concurrency:
    readers: [1, 2, 4, 8, 16, 32]
    writers: 0
  operations:
    write:
      event_size_bytes: 256
    read:
      limit: 10
  setup:
    prepopulate_events: 5000
    prepopulate_streams: 500
  stores:
    - umadb
    - kurrentdb
    - axonserver
    - eventsourcingdb
    - boomerang    
    - dummy
